// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "zero-template/api/internal/handler/auth"
	user "zero-template/api/internal/handler/user"
	"zero-template/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/self",
				Handler: user.UserSelfHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/token",
				Handler: auth.JwtTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)
}
